name: Desktop Applications Penetration Test
description: >-
  Third-party security assessment evaluating desktop application security through 
  systematic vulnerability testing including buffer overflows, privilege escalation, 
  insecure data storage, and client-side security issues with documented 
  remediation verification.
link: https://owasp.org/www-project-top-10/
icon:
  type: lucide
  lucideIcon: shield-check
type: resource
category: third_party_pen_tests
impact: infrastructure_security
