name: Desktop Applications Penetration Test
description: >-
  A third-party security assessment that evaluates the security posture of 
  desktop applications by testing for vulnerabilities such as buffer overflows, 
  privilege escalation, insecure data storage, and other client-side security 
  issues
link: https://owasp.org/www-project-top-10/
icon:
  type: lucide
  lucideIcon: shield-check
type: resource
category: third_party_pen_tests
impact: infrastructure_security
