name: Enterprise Guard Data Security
description: |
  Comprehensive data security architecture and controls documentation detailing
  Miro's enterprise-grade data protection measures, security architecture, and
  compliance framework for sensitive data handling and protection.
link:
icon:
  type: lucide
  lucideIcon: shield
type: resource
category: reports
impact: data_and_privacy
date: 2024-01-01