name: Mobile Applications Penetration Test
description: >-
  Third-party security assessment evaluating mobile applications (iOS/Android) 
  for vulnerabilities including insecure data storage, weak cryptography, 
  insecure communication, reverse engineering risks, and platform-specific 
  security issues with remediation verification.
link: https://owasp.org/www-project-mobile-security-testing-guide/
icon:
  type: lucide
  lucideIcon: shield-check
type: resource
category: third_party_pen_tests
impact: infrastructure_security
