name: Web Application and API Penetration Testing
description: >-
  Third-party security assessment validating web application and API security 
  through systematic vulnerability testing covering OWASP Top 10, authentication 
  mechanisms, authorization controls, input validation, and API-specific 
  security controls with documented remediation verification.
link: https://owasp.org/www-project-web-security-testing-guide/
icon:
  type: lucide
  lucideIcon: shield-check
type: resource
category: third_party_pen_tests
impact: infrastructure_security